### PR TITLE
Add note about nbgitpuller installed in environment

### PR DESCRIPTION
**Pull request by choldgraf**
One part of https://github.com/2i2c-org/infrastructure/issues/790 - this just adds a note that nbgitpuller needs to be installed

### CODE REVIEW

**Comment by damianavila** [comment]
Wondering if it makes sense for us to somehow "test" the images are compatible with us?

**Comment by damianavila** [comment]
The same goes with dasks-related packages for daskhub with custom images...

**Review by choldgraf — COMMENTED** [review]
I took another look at this and think it is good to self-merge. I agree @damianavila that it'd be good to test the environment somehow, but maybe as a part of another PR

**Review by choldgraf — COMMENTED** [review]
I took another look at this and think it is good to self-merge. I agree @damianavila that it'd be good to test the environment somehow, but maybe as a part of another PR

**Review by choldgraf — COMMENTED** [review]
I took another look at this and think it is good to self-merge. I agree @damianavila that it'd be good to test the environment somehow, but maybe as a part of another PR

**Review by choldgraf — COMMENTED** [review]
I took another look at this and think it is good to self-merge. I agree @damianavila that it'd be good to test the environment somehow, but maybe as a part of another PR

**Comment by damianavila** [comment]
It seems you took a lot of views, @choldgraf 😜

**Pull request merged**
